import Head from "next/head";
import fs from "fs";
import readline from "readline";
import React from "react";
import { count3MostCalories, countMostCalories } from "../utils/day1";
import { countRPSScore, countRPSScoreCorrectly } from "../utils/day2";
import { countPriorities, countPrioritiesInGroups } from "../utils/day3";
import { countOverlaps, countOverlaps2 } from "../utils/day4";
import { getTopOfStacks, getTopOfStacks2 } from "../utils/day5";
import { getMessageMarker, getPacketMarker } from "../utils/day6";
import { getFileSizes, getFileSizes2 } from "../utils/day7";
import { getVisibilityScore, getVisibleTrees } from "../utils/day8";
import { getRopePositions, getRopePositions2 } from "../utils/day9";
import { getSignal, getSignalStrength } from "../utils/day10";

type Props = {
  day1Input: string[];
  day2Input: string[];
  day3Input: string[];
  day4Input: string[];
  day5Input: string[];
  day6Input: string[];
  day7Input: string[];
  day8Input: string[];
  day9Input: string[];
  day10Input: string[];
};
const Home = (props: Props) => {
  const renderSignal = (input: string[]) => {
    const signal = getSignal(input);
    return (
      <div className="font-mono">
        {signal.map((line, i) => {
          return <div key={i}>{line.join("")}</div>;
        })}
      </div>
    );
  };
  return (
    <>
      <Head>
        <title>Advent of Code</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Advent of <span className="text-[hsl(280,100%,70%)]">Code</span>
          </h1>
          <h3 className="text-3xl font-extrabold tracking-tight text-white">
            made by{" "}
            <span className="text-5xl text-[hsl(80,100%,70%)]">Marpheus</span>
          </h3>
        </div>
        <div className="container mb-20 flex flex-col">
          <p className="pb-2 pt-2 text-2xl tracking-tight text-white">
            <span>Day 1, part 1: </span>
            <span>{countMostCalories(props.day1Input)}</span>
          </p>
          <p className="pb-2 pt-2  text-2xl tracking-tight text-white">
            <span>Day 1, part 2: </span>
            <span>{count3MostCalories(props.day1Input)}</span>
          </p>
          <hr />
          <p className="pb-2 pt-2 text-2xl tracking-tight text-white">
            <span>Day 2, part 1: </span>
            <span>{countRPSScore(props.day2Input)}</span>
          </p>
          <p className="pb-2 pt-2 text-2xl tracking-tight text-white">
            <span>Day 2, part 2: </span>
            <span>{countRPSScoreCorrectly(props.day2Input)}</span>
          </p>
          <hr />
          <p className="pb-2 pt-2 text-2xl tracking-tight text-white">
            <span>Day 3, part 1: </span>
            <span>{countPriorities(props.day3Input)}</span>
          </p>
          <p className="pb-2 pt-2 text-2xl tracking-tight text-white">
            <span>Day 2, part 2: </span>
            <span>{countPrioritiesInGroups(props.day3Input)}</span>
          </p>
          <hr />
          <p className="pb-2 pt-2 text-2xl tracking-tight text-white">
            <span>Day 4, part 1: </span>
            <span>{countOverlaps(props.day4Input)}</span>
          </p>
          <p className="pb-2 pt-2 text-2xl tracking-tight text-white">
            <span>Day 4, part 2: </span>
            <span>{countOverlaps2(props.day4Input)}</span>
          </p>
          <hr />
          <p className="pb-2 pt-2 text-2xl tracking-tight text-white">
            <span>Day 5, part 1: </span>
            <span>{getTopOfStacks(props.day5Input)}</span>
          </p>
          <p className="pb-2 pt-2 text-2xl tracking-tight text-white">
            <span>Day 5, part 2: </span>
            <span>{getTopOfStacks2(props.day5Input)}</span>
          </p>
          <hr />
          <p className="pb-2 pt-2 text-2xl tracking-tight text-white">
            <span>Day 6, part 1: </span>
            <span>{getPacketMarker(props.day6Input)}</span>
          </p>
          <p className="pb-2 pt-2 text-2xl tracking-tight text-white">
            <span>Day 6, part 2: </span>
            <span>{getMessageMarker(props.day6Input)}</span>
          </p>
          <hr />
          <p className="pb-2 pt-2 text-2xl tracking-tight text-white">
            <span>Day 7, part 1: </span>
            <span>{getFileSizes(props.day7Input)}</span>
          </p>
          <p className="pb-2 pt-2 text-2xl tracking-tight text-white">
            <span>Day 7, part 2: </span>
            <span>{getFileSizes2(props.day7Input)}</span>
          </p>
          <hr />
          <p className="pb-2 pt-2 text-2xl tracking-tight text-white">
            <span>Day 8, part 1: </span>
            <span>{getVisibleTrees(props.day8Input)}</span>
          </p>
          <p className="pb-2 pt-2 text-2xl tracking-tight text-white">
            <span>Day 8, part 2: </span>
            <span>{getVisibilityScore(props.day8Input)}</span>
          </p>
          <hr />
          <p className="pb-2 pt-2 text-2xl tracking-tight text-white">
            <span>Day 9, part 1: </span>
            <span>{getRopePositions(props.day9Input)}</span>
          </p>
          <p className="pb-2 pt-2 text-2xl tracking-tight text-white">
            <span>Day 9, part 2: </span>
            <span>{getRopePositions2(props.day9Input)}</span>
          </p>
          <hr />
          <p className="pb-2 pt-2 text-2xl tracking-tight text-white">
            <span>Day 10, part 1: </span>
            <span>{getSignalStrength(props.day10Input)}</span>
          </p>
          <div className="pb-2 pt-2 text-2xl tracking-tight text-white">
            <span>Day 10, part 2: </span>
            <>{renderSignal(props.day10Input)}</>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;

export async function getServerSideProps() {
  const loadInputFile = async (filePath: string) => {
    const input: string[] = [];
    const rl = readline.createInterface({
      input: fs.createReadStream(filePath),
      crlfDelay: Infinity,
    });
    rl.on("line", (line) => {
      input.push(line);
    });

    await new Promise((res) => rl.once("close", res));
    return input;
  };
  const day1Input: string[] = await loadInputFile("./src/inputs/day1.input");
  const day2Input: string[] = await loadInputFile("./src/inputs/day2.input");
  const day3Input: string[] = await loadInputFile("./src/inputs/day3.input");
  const day4Input: string[] = await loadInputFile("./src/inputs/day4.input");
  const day5Input: string[] = await loadInputFile("./src/inputs/day5.input");
  const day6Input: string[] = await loadInputFile("./src/inputs/day6.input");
  const day7Input: string[] = await loadInputFile("./src/inputs/day7.input");
  const day8Input: string[] = await loadInputFile("./src/inputs/day8.input");
  const day9Input: string[] = await loadInputFile("./src/inputs/day9.input");
  const day10Input: string[] = await loadInputFile("./src/inputs/day10.input");

  return {
    props: {
      day1Input,
      day2Input,
      day3Input,
      day4Input,
      day5Input,
      day6Input,
      day7Input,
      day8Input,
      day9Input,
      day10Input,
    },
  };
}
